name: ${env.REACT_APP_BUCKET}
myWebsite:
  component: '@serverless/website'
  inputs:
    code:
      src: ./build
      hook: yarn build
    region: ${env.AWS_REGION}
    bucketName: ${env.REACT_APP_BUCKET}
    domain: ${env.REACT_APP_DOMAIN}
