language: node_js
node_js:
  - 12
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
cache: yarn
before_install:
  - yarn global add codecov
install:
  - yarn install --frozen-lockfile
  - yarn cypress install
  - yarn cypress verify
script:
  - yarn lint
  - yarn coverage
  - cd packages/client
  - yarn cy:ci
  - yarn build
  - yarn lighthouse
  - cd ../../
after_success:
  - codecov --token="$CODECOV_TOKEN"
notifications:
  slack: $SLACK_TOKEN
deploy:
    - provider: script
    script: bash packages/client/deploy.sh
    edge: true
    on:
      branch: master
  - provider: script
    script: bash packages/services/deploy.sh
    edge: true
    on:
      branch: master
