language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
after_success:
  - codecov --token="$CODECOV_TOKEN"
notifications:
  slack: $SLACK_TOKEN
