language: node_js
node_js:
  - "stable"
addons:
  chrome: stable
  apt:
    packages:
    - libgconf-2-4
cache:
  directories:
    - node_modules
before_install:
  - npm install -g codecov
script:
  - npm run cy:ci
  - npm run coverage
  - npm run lint
  - npm run build
  - npm run lighthouse
after_success:
  - codecov --token="$CODECOV_TOKEN"
notifications:
  slack: $SLACK_TOKEN
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "buildit-poland-buddy-app"
  skip_cleanup: true
  local_dir: build
  acl: public_read
  on:
    branch: master
