language: node_js
node_js:
  - "stable"
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  directories:
    - node_modules
before_install:
  - npm install -g codecov
script:
  - npm run cy:ci
  - npm run coverage
  - npm run lint
  - npm run build
after_success:
  - codecov --token="$CODECOV_TOKEN"
notifications:
  slack: $SLACK_TOKEN
