language: node_js
node_js:
  - 12
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn global add codecov
script:
  - yarn lint
  - yarn coverage
  - yarn end2end
  - yarn build-client
  - yarn lighthouse
after_success:
  - codecov --token="$CODECOV_TOKEN"
notifications:
  slack: $SLACK_TOKEN
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "buildit-poland-buddy-app"
    region: eu-west-1
    local_dir: packages/client/build
    acl: public_read
    edge: true
    on:
      branch: master
  # deploy services
  - provider: script
    script: bash packages/services/deploy.sh prod
    edge: true
    on:
      branch: master
