enum ROUTES {
  BASE = '/',
  LOGIN = '/login',
  FORGOT_PASSWORD = '/forgot-password',
  RESET_PASSWORD = '/reset-password/:token',
  ROUTE_404 = '/404',

  TALENT = '/talent',
  TALENT_SELECT_BUDDY = '/talent/buddies',
  TALENT_SELECT_NEWBIE = '/talent/buddies/:buddyId/newbies',
  TALENT_ADD_TASK = '/talent/newbies/:newbieId/add-task',
  TALENT_TASK_DETAILS = '/talent/newbies/:newbieId/tasks/:taskId',
  TALENT_EDIT_TASK = '/talent/tasks/:taskId/edit-task',
  TALENT_TASKS_LIST = '/talent/newbies/:newbieId/tasks',
  TALENT_ADD_NEWBIE = '/talent/buddies/:buddyId/add-newbie',
  TALENT_ADD_BUDDY = '/talent/add-buddy',
  TALENT_ADD_TALENT = '/talent/add-talent',
  TALENT_DETAILS = '/talent/details',
  TALENT_EDIT_DETAILS = '/talent/edit-details',
  TALENT_BUDDY_DETAILS = '/talent/buddies/:buddyId/details',
  TALENT_EDIT_BUDDY_DETAILS = '/talent/buddies/:buddyId/edit-details',
  TALENT_NEWBIE_DETAILS = '/talent/newbies/:newbieId/details',
  TALENT_EDIT_NEWBIE_DETAILS = '/talent/newbies/:newbieId/edit-details',

  BUDDY = '/buddy/',
  BUDDY_DETAILS = '/buddy/details',
  BUDDY_EDIT_DETAILS = '/buddy/edit-details',
  BUDDY_ADD_TASK = '/buddy/newbies/:newbieId/add-task',
  BUDDY_TASK_DETAILS = '/buddy/newbies/:newbieId/tasks/:taskId',
  BUDDY_EDIT_TASK = '/buddy/tasks/:taskId/edit-task',
  BUDDY_TASKS_LIST = '/buddy/newbies/:newbieId/tasks',
  BUDDY_SELECT_NEWBIE = '/buddy/newbies',
  BUDDY_ADD_NEWBIE = '/buddy/add-newbie',
  BUDDY_NEWBIE_DETAILS = '/buddy/newbies/:newbieId/details',
  BUDDY_EDIT_NEWBIE_DETAILS = '/buddy/newbies/:newbieId/edit-details',

  NEWBIE = '/newbie',
  NEWBIE_DETAILS = '/newbie/details',
  NEWBIE_EDIT_DETAILS = '/newbie/edit-details',
  NEWBIE_TASKS_LIST = '/newbie/newbies/:newbieId/tasks',
  NEWBIE_TASK_DETAILS = '/newbie/newbies/:newbieId/tasks/:taskId',
  NEWBIE_BUDDY_DETAILS = '/newbie/buddies/:buddyId/details',
}

export { ROUTES };
