service:
  name: buildit-poland-buddy-app-services
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    PRISMA_ENDPOINT: ${env:PRISMA_ENDPOINT}
    PRISMA_STAGE: ${env:PRISMA_STAGE}
    PRISMA_SECRET: ${env:PRISMA_SECRET}
    APP_SECRET: ${env:APP_SECRET}
    API_GATEWAY_DOMAIN: ${env:API_GATEWAY_DOMAIN}
    ACCESS_KEY: ${env:AWS_ACCESS_KEY_ID}
    SECRET_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    REGION: ${env:AWS_REGION}
    EMAIL: ${env:EMAIL}
  profile: default
package:
  excludeDevDependencies: true
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-offline
custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    packager: yarn
    includeModules:
      forceExclude:
        - typescript
  serverless-offline:
    port: 4000
  domains:
    prod: ${env:API_GATEWAY_DOMAIN}
    dev: ${env:API_GATEWAY_DOMAIN}
  customDomain:
    basePath: "${self:custom.stage}"
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    createRoute53Record: true
  funcsPerStage:
    prod:
      graphql:
        handler: src/handler.graphql
        events:
          - http:
              path: "/"
              method: post
              cors: true
    dev:
      graphql:
        handler: src/handler.graphql
        events:
          - http:
              path: "/"
              method: post
              cors: true
      playground:
        handler: src/handler.graphqlPlayground
        events:
          - http:
              path: /graphql
              method: get
              cors: true

functions: ${self:custom.funcsPerStage.${self:custom.stage}}
