service:
  name: buildit-poland-buddy-app
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    port: 4000

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  graphql:
    handler: src/handler.graphqlHandler
    description: graphql api for ${self:service.name}
    events:
    - http:
        path: /graphql
        method: post
        cors: true
  playground:
    handler: src/handler.playgroundHandler
    description: graphql playground api for ${self:service.name}
    events:
    - http:
        path: /graphql
        method: get
        cors: true
