service: buddy-app-graphql
package:
  exclude:
    - node_modules/**/*
  include:
    src/handler.ts
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

custom:
  serverless-offline:
    port: 4000
functions:
  graphql:
    # PRISMA_ENDPOINT: ${env:PRISMA_ENDPOINT}
    # PRISMA_SECRET: ${env:PRISMA_SECRET}
    # APP_SECRET: ${env:APP_SECRET}
    handler: handler.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
  playground:
    # PRISMA_ENDPOINT: ${env:PRISMA_ENDPOINT}
    # PRISMA_SECRET: ${env:PRISMA_SECRET}
    # APP_SECRET: ${env:APP_SECRET}
    handler: handler.playground
    events:
    - http:
        path: /
        method: get
        cors: true
