service:
  name: buddy-app
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    port: 4000
  dotenv:
    path: ./.env.development
    basePath: ./
    include:
      - PRISMA_ENDPOINT
      - PRISMA_SECRET
      - APP_SECRET

# Add the serverless-webpack plugin
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
    - http:
        path: /graphql
        method: post
        cors: true
  playground:
    handler: src/handler.playgroundHandler
    events:
    - http:
        path: /graphql
        method: get
        cors: true
